// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzgzbxttwstgnantovpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Z3pieHR0d3N0Z25hbnRvdnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MTg3ODQsImV4cCI6MjA3NzQ5NDc4NH0.TE_YEeHrbc8jjUKZJ3a7jxvCFm9Se02S1ZE9QQc7Kh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});